services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:18
    container_name: cursos-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/cursos_matriculas.csv:/docker-entrypoint-initdb.d/cursos_matriculas.csv

volumes:
  pgdata:
